spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082

app:
  kafka:
    topic: "orders"
    groupId: "order-group-id"
    partitions: 3
    replicas: 1
    max-pull-records: 10

  retry:
    max-attempts: 3
    delay: 1000