spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: ${HOST:localhost}:${KAFKA1_PORT:9092}, ${HOST:localhost}:${KAFKA2_PORT:9093}, ${HOST:localhost}:${KAFKA3_PORT:9094}

  web:
    client:
      rest:
        connect-timeout: 5s
        read-timeout: 10s

server:
  port: 8081

app:
  kafka:
    topic: orders
    dlt-topic: orders.DLT
    partitions: 3
    replicas: 3

  data:
    service:
      url:
        api: http://${HOST:localhost}:8083/api/data

  retry:
    max-attempts: 3
    delay: 1000
    multiplier: 2
    max-interval: 10000

logging:
  level:
    com.github.seecret1.data: DEBUG
    com.github.seecret1.order_service: DEBUG
    com.github.seecret1.notification_service: DEBUG
